# Generated by Django 6.1.1 on 2026-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('semester', models.CharField(max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
