# Generated by Django 6.1.1 on 2026-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
